//structured data from the page http://www.kaymont.com/pages/sounding-balloons.cfm
var specs = {
    'KCI 200' : {
        'Average Weight (gr)'               : 200,
        'Neck Diameter (cm)'                : 3,
        'Neck Length (cm)'                  : 12,
        'Flaccid Body Length more(cm)'      : 86,
        'Barely Inflated Diameter more(cm)' : 55,
        'Payload (gr)'                      : 250,
        'Recommended Free Lift (gr)'        : 510,
        'Nozzle Lift (gr)'                  : 760,
        'Gross Lift (gr)'                   : 960,
        'Diameter at Release (cm)'          : 117,
        'Volume at Release (cu. m)'         : 0.83,
        'Rate of Ascent (m.min)'            : 320,
        'Diameter at Burst (cm)'            : 300,
        'Bursting Altitude (km)'            : 21.2,
        'Bursting Pressure (hPa)'           : 45.3
    },
    'KCI 300' : {
        'Average Weight (gr)'               : 300,
        'Neck Diameter (cm)'                : 3,
        'Neck Length (cm)'                  : 12,
        'Flaccid Body Length more(cm)'      : 108,
        'Barely Inflated Diameter more(cm)' : 69,
        'Payload (gr)'                      : 250,
        'Recommended Free Lift (gr)'        : 560,
        'Nozzle Lift (gr)'                  : 810,
        'Gross Lift (gr)'                   : 1110,
        'Diameter at Release (cm)'          : 123,
        'Volume at Release (cu. m)'         : 0.97,
        'Rate of Ascent (m.min)'            : 320,
        'Diameter at Burst (cm)'            : 378,
        'Bursting Altitude (km)'            : 24.7,
        'Bursting Pressure (hPa)'           : 26.3
    },
    'KCI 350' : {
        'Average Weight (gr)'               : 350,
        'Neck Diameter (cm)'                : 3,
        'Neck Length (cm)'                  : 12,
        'Flaccid Body Length more(cm)'      : 118,
        'Barely Inflated Diameter more(cm)' : 75,
        'Payload (gr)'                      : 250,
        'Recommended Free Lift (gr)'        : 585,
        'Nozzle Lift (gr)'                  : 835,
        'Gross Lift (gr)'                   : 1185,
        'Diameter at Release (cm)'          : 125,
        'Volume at Release (cu. m)'         : 1.03,
        'Rate of Ascent (m.min)'            : 320,
        'Diameter at Burst (cm)'            : 412,
        'Bursting Altitude (km)'            : 25.9,
        'Bursting Pressure (hPa)'           : 21.9
    },
    'KCI 450' : {
        'Average Weight (gr)'               : 450,
        'Neck Diameter (cm)'                : 3,
        'Neck Length (cm)'                  : 12,
        'Flaccid Body Length more(cm)'      : 125,
        'Barely Inflated Diameter more(cm)' : 86,
        'Payload (gr)'                      : 250,
        'Recommended Free Lift (gr)'        : 635,
        'Nozzle Lift (gr)'                  : 885,
        'Gross Lift (gr)'                   : 1335,
        'Diameter at Release (cm)'          : 130,
        'Volume at Release (cu. m)'         : 1.1,
        'Rate of Ascent (m.min)'            : 320,
        'Diameter at Burst (cm)'            : 472,
        'Bursting Altitude (km)'            : 27.7,
        'Bursting Pressure (hPa)'           : 16.6
    },
    'KCI 500' : {
        'Average Weight (gr)'               : 500,
        'Neck Diameter (cm)'                : 3,
        'Neck Length (cm)'                  : 12,
        'Flaccid Body Length more(cm)'      : 143,
        'Barely Inflated Diameter more(cm)' : 91,
        'Payload (gr)'                      : 250,
        'Recommended Free Lift (gr)'        : 655,
        'Nozzle Lift (gr)'                  : 905,
        'Gross Lift (gr)'                   : 1405,
        'Diameter at Release (cm)'          : 133,
        'Volume at Release (cu. m)'         : 1.22,
        'Rate of Ascent (m.min)'            : 320,
        'Diameter at Burst (cm)'            : 499,
        'Bursting Altitude (km)'            : 28.4,
        'Bursting Pressure (hPa)'           : 14.9
    },
    'KCI 600' : {
        'Average Weight (gr)'               : 600,
        'Neck Diameter (cm)'                : 3,
        'Neck Length (cm)'                  : 12,
        'Flaccid Body Length more(cm)'      : 157,
        'Barely Inflated Diameter more(cm)' : 100,
        'Payload (gr)'                      : 250,
        'Recommended Free Lift (gr)'        : 870,
        'Nozzle Lift (gr)'                  : 1120,
        'Gross Lift (gr)'                   : 1720,
        'Diameter at Release (cm)'          : 142,
        'Volume at Release (cu. m)'         : 1.5,
        'Rate of Ascent (m.min)'            : 320,
        'Diameter at Burst (cm)'            : 602,
        'Bursting Altitude (km)'            : 30.8,
        'Bursting Pressure (hPa)'           : 10.4
    },
    'KCI 700' : {
        'Average Weight (gr)'               : 700,
        'Neck Diameter (cm)'                : 3,
        'Neck Length (cm)'                  : 12,
        'Flaccid Body Length more(cm)'      : 171,
        'Barely Inflated Diameter more(cm)' : 109,
        'Payload (gr)'                      : 250,
        'Recommended Free Lift (gr)'        : 920,
        'Nozzle Lift (gr)'                  : 1170,
        'Gross Lift (gr)'                   : 1870,
        'Diameter at Release (cm)'          : 146,
        'Volume at Release (cu. m)'         : 1.63,
        'Rate of Ascent (m.min)'            : 320,
        'Diameter at Burst (cm)'            : 653,
        'Bursting Altitude (km)'            : 31.8,
        'Bursting Pressure (hPa)'           : 8.9
    },
    'KCI 800' : {
        'Average Weight (gr)'               : 800,
        'Neck Diameter (cm)'                : 3,
        'Neck Length (cm)'                  : 12,
        'Flaccid Body Length more(cm)'      : 184,
        'Barely Inflated Diameter more(cm)' : 117,
        'Payload (gr)'                      : 250,
        'Recommended Free Lift (gr)'        : 970,
        'Nozzle Lift (gr)'                  : 1220,
        'Gross Lift (gr)'                   : 2020,
        'Diameter at Release (cm)'          : 150,
        'Volume at Release (cu. m)'         : 1.76,
        'Rate of Ascent (m.min)'            : 320,
        'Diameter at Burst (cm)'            : 700,
        'Bursting Altitude (km)'            : 32.6,
        'Bursting Pressure (hPa)'           : 7.6
    },
    'KCI 1000' : {
        'Average Weight (gr)'               : 1000,
        'Neck Diameter (cm)'                : 3,
        'Neck Length (cm)'                  : 12,
        'Flaccid Body Length more(cm)'      : 206,
        'Barely Inflated Diameter more(cm)' : 131,
        'Payload (gr)'                      : 250,
        'Recommended Free Lift (gr)'        : 1060,
        'Nozzle Lift (gr)'                  : 1310,
        'Gross Lift (gr)'                   : 2310,
        'Diameter at Release (cm)'          : 157,
        'Volume at Release (cu. m)'         : 2.01,
        'Rate of Ascent (m.min)'            : 320,
        'Diameter at Burst (cm)'            : 786,
        'Bursting Altitude (km)'            : 33.9,
        'Bursting Pressure (hPa)'           : 6.6
    },
    'KCI 1200' : {
        'Average Weight (gr)'               : 1200,
        'Neck Diameter (cm)'                : 3,
        'Neck Length (cm)'                  : 12,
        'Flaccid Body Length more(cm)'      : 226,
        'Barely Inflated Diameter more(cm)' : 144,
        'Payload (gr)'                      : 1050,
        'Recommended Free Lift (gr)'        : 1190,
        'Nozzle Lift (gr)'                  : 2240,
        'Gross Lift (gr)'                   : 3440,
        'Diameter at Release (cm)'          : 179,
        'Volume at Release (cu. m)'         : 2.99,
        'Rate of Ascent (m.min)'            : 320,
        'Diameter at Burst (cm)'            : 863,
        'Bursting Altitude (km)'            : 33.2,
        'Bursting Pressure (hPa)'           : 7.3
    },
    'KCI 1500' : {
        'Average Weight (gr)'               : 1500,
        'Neck Diameter (cm)'                : 3,
        'Neck Length (cm)'                  : 12,
        'Flaccid Body Length more(cm)'      : 253,
        'Barely Inflated Diameter more(cm)' : 161,
        'Payload (gr)'                      : 1050,
        'Recommended Free Lift (gr)'        : 1280,
        'Nozzle Lift (gr)'                  : 2330,
        'Gross Lift (gr)'                   : 3830,
        'Diameter at Release (cm)'          : 185,
        'Volume at Release (cu. m)'         : 3.33,
        'Rate of Ascent (m.min)'            : 320,
        'Diameter at Burst (cm)'            : 944,
        'Bursting Altitude (km)'            : 34.2,
        'Bursting Pressure (hPa)'           : 6.3
    },
    'KCI 2000' : {
        'Average Weight (gr)'               : 2000,
        'Neck Diameter (cm)'                : 5,
        'Neck Length (cm)'                  : 18,
        'Flaccid Body Length more(cm)'      : 289,
        'Barely Inflated Diameter more(cm)' : 184,
        'Payload (gr)'                      : 1050,
        'Recommended Free Lift (gr)'        : 1420,
        'Nozzle Lift (gr)'                  : 2470,
        'Gross Lift (gr)'                   : 4470,
        'Diameter at Release (cm)'          : 195,
        'Volume at Release (cu. m)'         : 3.89,
        'Rate of Ascent (m.min)'            : 320,
        'Diameter at Burst (cm)'            : 1054,
        'Bursting Altitude (km)'            : 35.4,
        'Bursting Pressure (hPa)'           : 5.3
    },
    'KCI 3000' : {
        'Average Weight (gr)'               : 3000,
        'Neck Diameter (cm)'                : 5,
        'Neck Length (cm)'                  : 18,
        'Flaccid Body Length more(cm)'      : 357,
        'Barely Inflated Diameter more(cm)' : 227,
        'Payload (gr)'                      : 1050,
        'Recommended Free Lift (gr)'        : 1670,
        'Nozzle Lift (gr)'                  : 2720,
        'Gross Lift (gr)'                   : 5720,
        'Diameter at Release (cm)'          : 212,
        'Volume at Release (cu. m)'         : 4.97,
        'Rate of Ascent (m.min)'            : 320,
        'Diameter at Burst (cm)'            : 1300,
        'Bursting Altitude (km)'            : 37.9,
        'Bursting Pressure (hPa)'           : 3.7
    },
};
